### PR TITLE
Implemented online features

### PR DESCRIPTION
**Pull request by GDcheeriosYT**
This is going to be sick!

### CODE REVIEW

**Comment by GDcheeriosYT** [comment]
currently need to fix this:

```
Traceback (most recent call last):
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\main.py", line 80, in <module>
    server.API.upload_data(game.game_data)
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\Online\API\API.py", line 46, in upload_data
    upload_data(self.url, self.id, data, self.token.token)
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\Online\API\UploadData.py", line 6, in upload_data
    requests.post(f"{url}/api/account/updateGCdata/{id}", json={"token": token, "data":data.jsonify()})
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\GameData.py", line 102, in jsonify
    "inventory": self.inventory.jsonify()
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\Collection\Inventory\Inventory.py", line 304, in jsonify
    "artifacts": self.jsonify(),
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\Collection\Inventory\Inventory.py", line 304, in jsonify
    "artifacts": self.jsonify(),
  File "C:\Users\minec\github-shit\New folder\Gentrys-Quest-Python\game\Collection\Inventory\Inventory.py", line 304, in jsonify
    "artifacts": self.jsonify(),
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
```

this happens when uploading data.

**Comment by bm38573** [comment]
I think I can try fixing this inventory josnify issue.

**Comment by bm38573** [comment]
bro, someone removed the return statement to the `ItemList.jsonify()` method...

**Comment by bm38573** [comment]
so this isn't even just this branch. I think It might have been from #47. I'll check the differences.

**Comment by bm38573** [comment]
dude, who ever was writing this must've had zero and I mean ZERO sleep. This is absolutely stupid. it was referring to `Inventory.jsonify()` rather than the `ItemLists` inside.

**Comment by bm38573** [comment]
I feel it might be dangerous to uplad data apon an exception or the program exitting because something might happen whilst generating an item and then make the json incorrect and then ruin all the data of a player.

**Pull request merged**
